global proc loction(int $running){
    string $locFilePath = `whatIs loction`;
    string $projectPath = `substring $locFilePath 25 (size($locFilePath)-22)`;
    $projectPath = substituteAllString($projectPath, "\\", "/");
    string $pyCommand = "execfile('"+$projectPath+"/OldCat/Awake/Roll.py')\n__run_from('"+$projectPath+"')";
    print($pyCommand);
    python($pyCommand);
}

evalDeferred -lp "loction(0)";
